CWD := $(shell readlink -f ./)

BUILD_OUTPUT_FOLDER := $(CWD)/build
LINUX_BUILD_OUTPUT_FOLDER := $(BUILD_OUTPUT_FOLDER)/linux

OUTPUT_OPENPA_STATIC_LIB_FOLDER := $(LINUX_BUILD_OUTPUT_FOLDER)/openpa
OUTPUT_OPENPA_STATIC_LIB := $(OUTPUT_OPENPA_STATIC_LIB_FOLDER)/libopenpa.a

OUTPUT_SFW_LIB_FOLDER := $(LINUX_BUILD_OUTPUT_FOLDER)/sfw
OUTPUT_SFW_LIB := $(OUTPUT_SFW_LIB_FOLDER)/sfw.so

OUTPUT_TEST_CONSOLE_FOLDER := $(LINUX_BUILD_OUTPUT_FOLDER)/test-console
OUTPUT_TEST_CONSOLE := $(OUTPUT_TEST_CONSOLE_FOLDER)/test-console

OUTPUT_SWF_NET_FOLDER := $(LINUX_BUILD_OUTPUT_FOLDER)/sfw.net
OUTPUT_SWF_NET_TEST_CONSOLE_FOLDER := $(LINUX_BUILD_OUTPUT_FOLDER)/sfw.net.TestConsole

OPENPA_PROJECT_OUTPUT_FOLDER := openpa/out
SFW_PROJECT_OUTPUT_FOLDER := sfw/build
TEST_CONSOLE_PROJECT_OUTPUT_FOLDER := test-console/build

all:
	mkdir -p $(BUILD_OUTPUT_FOLDER)
	mkdir -p $(LINUX_BUILD_OUTPUT_FOLDER)
	
	## OPENPA
	
	mkdir -p $(OUTPUT_OPENPA_STATIC_LIB_FOLDER)
	
	$(MAKE) -C openpa all CFLAGS=-fpic
	cp -urv $(OPENPA_PROJECT_OUTPUT_FOLDER)/Default/obj.target/* $(OUTPUT_OPENPA_STATIC_LIB_FOLDER)
	
	## SFW
	
	mkdir -p $(OUTPUT_SFW_LIB_FOLDER)

	$(MAKE) -C sfw all OPENPA_STATIC_LIB=$(OUTPUT_OPENPA_STATIC_LIB)
	cp -urv $(SFW_PROJECT_OUTPUT_FOLDER)/linux/* $(OUTPUT_SFW_LIB_FOLDER)
	
	## TEST-CONSOLE
	
	mkdir -p $(OUTPUT_TEST_CONSOLE_FOLDER)

	$(MAKE) -C test-console all OUTPUT_SFW_LIB=$(OUTPUT_SFW_LIB)
	cp -urv $(TEST_CONSOLE_PROJECT_OUTPUT_FOLDER)/linux/* $(OUTPUT_TEST_CONSOLE_FOLDER)

	## SFW.NET
	
	mkdir -p $(OUTPUT_SWF_NET_FOLDER)

	mkdir -p $(OUTPUT_SWF_NET_FOLDER)/Debug
	cp -uv $(OUTPUT_SFW_LIB) $(OUTPUT_SWF_NET_FOLDER)/Debug

	mkdir -p $(OUTPUT_SWF_NET_FOLDER)/Release
	cp -uv $(OUTPUT_SFW_LIB) $(OUTPUT_SWF_NET_FOLDER)/Release

	## SFW.NET.TEST-CONSOLE
	
	mkdir -p $(OUTPUT_SWF_NET_TEST_CONSOLE_FOLDER)

	mkdir -p $(OUTPUT_SWF_NET_TEST_CONSOLE_FOLDER)/Debug
	cp -uv $(OUTPUT_SFW_LIB) $(OUTPUT_SWF_NET_TEST_CONSOLE_FOLDER)/Debug

	mkdir -p $(OUTPUT_SWF_NET_TEST_CONSOLE_FOLDER)/Release
	cp -uv $(OUTPUT_SFW_LIB) $(OUTPUT_SWF_NET_TEST_CONSOLE_FOLDER)/Release
	
clean:
	rm -rf $(OPENPA_PROJECT_OUTPUT_FOLDER) $(SFW_PROJECT_OUTPUT_FOLDER) $(TEST_CONSOLE_PROJECT_OUTPUT_FOLDER) $(BUILD_OUTPUT_FOLDER)
